### ISSUE TITLE
Exception ImproperlyConfigured trying to instantiate a DataTableView embedded in an unrelated template

### ISSUE THREAD

**Issue by bobhy** [pivotal-energy-solutions/django-datatable-view#115]
Hi All,
I’m trying to create a TemplateView which has a bunch of simple widgets followed by 2 embedded DataTableViews, following the sample ‘SatelliteDataTableView’.  I keep getting the above exception after trying several things, so would appreciate some suggestions about how to do embedded views.

But in this code:

``` python
## this is my desired ‘embedded’ Datatable
class FileDatatable( Datatable):
    class Meta:
        columns = ['directory', 'name' , 'size' , 'creDate' , 'modDate']
        structure_template = "dtUi/bootstrap_structure.html"

## this is my desired ‘satellite’ view
class FileDatatableView( DatatableView):
    model = File
    datatable_class = FileDatatable
    template_name = 'dtui/file_list.html'

    ## added this method as my second try, after peeking at the actual sample code (as opposed to the documented implementation), but no help.
    def get_datatable_kwargs(self):
        """added to the vanilla view to make the view embeddable via instantiation.  See py:class:`FormWithTablesView` below."""
        kwargs = super(FileDatatableView, self).get_datatable_kwargs()
        kwargs['url'] = reverse('dtUi:first_try')       ## a bit ugly that the view can only be attached to one URL
        kwargs['template_name'] = 'dtui/file_list.html'
        return kwargs
    ## added this method as my third try, believing the text of the error message.  Also no help.
    def get_template_names(self):
        """
        Also added to support embeddable view.  Still don't know why, though.
        """
        return ['dtui/file_list.html']

## this is my desired master view with 2 Datatables (removed the other widgets in the interest of simplicity)
class FormWithTablesView( TemplateView):
    template = 'dtUi/form_with_tables.html'

    def get_context_data(self, **kwargs):
        context = super(FormWithTablesView, self).get_context_data(**kwargs)

        context['ftTable'] = FileDatatableView().get_datatable()
     ## the first error I actually got pertained to missing URL definition.  I was able to get past that with the following:
        ##context['ftTable'] = FileDatatableView().get_datatable(url=reverse(‘dtui/file_list.html’))
     ## but then I encountered the persistent template_name issue…

        context['ftelTable'] = FileDatatableView_EditLink().get_datatable() ## assume that FileDatatableView_EditLink is a copy of FileDatatableView with different columns.
        return context
```

I’m blocked by this exception: 

```
Internal Server Error: /ui/fwt/
Traceback (most recent call last):
  File "N:\vePython\django\lib\site-packages\django\core\handlers\base.py", line 132, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "N:\vePython\django\lib\site-packages\django\views\generic\base.py", line 71, in view
    return self.dispatch(request, *args, **kwargs)
  File "N:\vePython\django\lib\site-packages\django\views\generic\base.py", line 89, in dispatch
    return handler(request, *args, **kwargs)
  File "N:\vePython\django\lib\site-packages\django\views\generic\base.py", line 159, in get
    return self.render_to_response(context)
  File "N:\vePython\django\lib\site-packages\django\views\generic\base.py", line 133, in render_to_response
    template=self.get_template_names(),
  File "N:\vePython\django\lib\site-packages\django\views\generic\base.py", line 146, in get_template_names
    "TemplateResponseMixin requires either a definition of "
django.core.exceptions.ImproperlyConfigured: TemplateResponseMixin requires either a definition of 'template_name' or an implementation of 'get_template_names()'
[16/Nov/2015 21:09:07] "GET /ui/fwt/ HTTP/1.1" 500 98707
```

I’m running these versions of things:

Python 3.5.0 (v3.5.0:374f501f4567, Sep 13 2015, 02:27:37) [MSC v.1900 64 bit (AMD64)] on win32
Django (1.8.6)
django-datatable-view (0.9.0b5, n:\devwork\django\django-datatable-view)

And, as you can see, I’m pretty far off in the weeds and have no clue how to proceed.
Any suggestions you offer will be gratefully accepted.

Regards,
Bob

**Comment by bobhy** [comment]
Ah, neglected to mention I'm using datatables.js 1.10.10
--b

**Comment by tiliv** [comment]
Could this be just a typo on the last class you showed?

```python
class FormWithTablesView( TemplateView):
    template = 'dtUi/form_with_tables.html'
    # ...
```

``template`` should be ``template_name`` here.  It looks like you've got it right on the actual datatable view, so I just wanted to double check that.  If that's the case, then this is probably just Django raising its own internal exception, rather than one raised by django-datatable-view

Let me know!

**Comment by bobhy** [comment]
Why, yes!  That’s exactly what it was.

 

OK, now I’m on to the next error: the page loads, but now raises an alert dialog Cannot re-initialize Datatable options (http://datatables.net/manual/tech-notes/3).

I won’t have time to debug this till later tonight.  I guess each view needs to have a distinct name for its datatable JS object on the page.  Hmm, if this is so, it would be nice if Django-datatable-view constructed each view with a unique name for its datatable object.

 

Regards,

Bob
