### ISSUE TITLE
Several problems running the example_project under django 1.9.2

### ISSUE THREAD

**Issue by stezz** [pivotal-energy-solutions/django-datatable-view#125]
Hi there,

wanted to test datatable-view in a virtualenv and I have faced few problems following the instructions.

```
$ git clone https://github.com/pivotal-energy-solutions/django-datatable-view.git
$ cd django-datatable-view
$ mkvirtualenv datatableview
(datatableview)$ pip install -r requirements.txt
```
Seems to have  a bit old requirements:
```
You are using pip version 6.0.8, however version 8.0.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Collecting django>=1.4 (from -r requirements.txt (line 1))
  Using cached Django-1.9.2-py2.py3-none-any.whl
Collecting python-dateutil>=2.1 (from -r requirements.txt (line 2))
  Using cached python_dateutil-2.4.2-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil>=2.1->-r requirements.txt (line 2))
  Using cached six-1.10.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, django

Successfully installed django-1.9.2 python-dateutil-2.4.2 six-1.10.0
```
When running:
```
datatableview/tests/example_project/manage.py syncdb
Traceback (most recent call last):
  File "datatableview/tests/example_project/manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named datatableview
```
This gets workedaround by:
```
cd datatableview/tests/example_project/ && python manage.py syncdb
```
But

```
python manage.py syncdb
Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/__init__.py", line 327, in execute
    django.setup()
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/__init__.py", line 18, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/apps/registry.py", line 85, in populate
    app_config = AppConfig.create(entry)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/apps/config.py", line 90, in create
    module = import_module(entry)
  File "/usr/lib64/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/<user>/django-datatable-view/datatableview/__init__.py", line 3, in <module>
    from .datatables import Datatable, ValuesDatatable, LegacyDatatable
  File "/home/<user>/django-datatable-view/datatableview/datatables.py", line 29, in <module>
    from .columns import (Column, TextColumn, DateColumn, DateTimeColumn, BooleanColumn, IntegerColumn,
  File "/home/<user>/django-datatable-view/datatableview/columns.py", line 18, in <module>
    from django.forms.util import flatatt
ImportError: No module named util
```
seems in django 1.9.2 that module is django.forms.utils not util. After modifying columns.py I am able to run it, almost, since syncdb is substituted by makemigrations & migrate in 1.9.2:
```
(datatableview)[<user>@localhost example_project]$ python manage.py syncdb
Unknown command: 'syncdb'
Type 'manage.py help' for usage.
(datatableview)[<user>@localhost example_project]$ python manage.py makemigrations example_app
/home/<user>/django-datatable-view/datatableview/tests/example_project/example_project/example_app/urls.py:28: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  *urls

/home/<user>/django-datatable-view/datatableview/tests/example_project/example_project/urls.py:6: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^', include('example_project.example_app.urls')),

Migrations for 'example_app':
  0001_initial.py:
    - Create model Author
    - Create model Blog
    - Create model Entry
(datatableview)[<user>@localhost example_project]$ python manage.py migrate
/home/<user>/django-datatable-view/datatableview/tests/example_project/example_project/example_app/urls.py:28: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  *urls

/home/<user>/django-datatable-view/datatableview/tests/example_project/example_project/urls.py:6: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^', include('example_project.example_app.urls')),

Operations to perform:
  Apply all migrations: example_app
Running migrations:
  Rendering model states... DONE
  Applying example_app.0001_initial... OK
(datatableview)[<user>@localhost example_project]$ 
```
And then last but not least:

```
(datatableview)$ datatableview/tests/example_project/manage.py loaddata initial_data_modern
```
which gives some more issues:
```
(datatableview)[<user>@localhost example_project]$ python manage.py loaddata initial_data_modern/home/<user>/django-datatable-view/datatableview/tests/example_project/example_project/example_app/urls.py:28: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  *urls

/home/<user>/django-datatable-view/datatableview/tests/example_project/example_project/urls.py:6: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^', include('example_project.example_app.urls')),

Traceback (most recent call last):
  File "manage.py", line 11, in <module>
    execute_from_command_line(sys.argv)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
    utility.execute()
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/__init__.py", line 345, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/base.py", line 348, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/base.py", line 399, in execute
    output = self.handle(*args, **options)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 100, in loaddata
    self.load_label(fixture_label)
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/management/commands/loaddata.py", line 152, in load_label
    for obj in objects:
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/serializers/json.py", line 85, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/serializers/json.py", line 79, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/serializers/python.py", line 96, in Deserializer
    Model = _get_model(d["model"])
  File "/home/<user>/.virtualenvs/datatableview/lib/python2.7/site-packages/django/core/serializers/python.py", line 187, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
django.core.serializers.base.DeserializationError: Problem installing fixture '/home/<user>/django-datatable-view/datatableview/tests/example_project/example_project/example_app/fixtures/initial_data_modern.json': Invalid model identifier: 'datatableview.Blog'
```

And here it seems that in the initial_data_modern.json fixture datatableview has to be subsituted with 'example_app' (since the model belongs to that app not to datatableview). After that modification I am almost there.
```
(datatableview)[<user>@localhost example_project]$ python manage.py loaddata initial_data_modern/home/<user>/django-datatable-view/datatableview/tests/example_project/example_project/example_app/urls.py:28: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  *urls

/home/<user>/django-datatable-view/datatableview/tests/example_project/example_project/urls.py:6: RemovedInDjango110Warning: django.conf.urls.patterns() is deprecated and will be removed in Django 1.10. Update your urlpatterns to be a list of django.conf.urls.url() instances instead.
  url(r'^', include('example_project.example_app.urls')),

Installed 10 object(s) from 1 fixture(s)
```

And then
```
(datatableview)$ datatableview/tests/example_project/manage.py runserver
```
Has all kinds of issues mainly because 
```
    'django.contrib.auth',
    'django.contrib.contenttypes',
```

Are disabled in INSTALLED_APPS. Enabling them make the test example work (so far :)).

Not sure if I have done something unorthodox here but it took me a good 30 minutes to get the test example started under 1.9.2 while it seemed the test environment was meant to run out of the box.

**Comment by stezz** [comment]
Suggest some fixes in the commit above. And I noticed that the warnings on the requirements have nothing to do with requirements.txt but are local issues, so disregard that.

**Comment by doganmeh** [comment]
django-datatable-view does not have pip requirement, so that is related to your system.

The following may ease the rest of the process:

1) Check out this branch, it has compatibility with django 1.9: https://github.com/jangeador/django-datatable-view/, or instead you could just update the requirements file to use Django 1.8 instead (i.e., Django==1.8). By the way, you may also have to use python 3.X. 

2) Instead of syncdb, use ./manage.py migrate (make sure to have rw access to the project folder as this will place the db file in there)

3) Afterwards, use loaddata and load the legacy fixture, not the modern one. 

This is how it worked for me.
