### ISSUE TITLE
Ajax call blows up when searched 'true' or 'false' on a Datatable including a BooleanColumn

### ISSUE THREAD

**Issue by doganmeh** [pivotal-energy-solutions/django-datatable-view#141]
My model (pretty much the django's User class):

    class Person(AbstractUser):
        """Actual people in a school"""
    
        position = models.ForeignKey(Position, blank=True, null=True)
        school = models.ForeignKey(School, blank=True, null=True)
        is_school_contact = models.BooleanField(default=False, verbose_name='School Contact?')
        phone = models.CharField(max_length=10, blank=True, null=True)
        extension = models.CharField(max_length=10, blank=True, null=True)
        is_pending = models.BooleanField(default=True, blank=True, verbose_name='Pending?')

And my Datatable and DatatableView:

    class PersonDataTable(Datatable):
        school = columns.TextColumn(sources=['school__name'])
        is_active = columns.BooleanColumn(sources='is_active', processor=get_bool_check_mark),
        is_pending = columns.BooleanColumn(sources='is_pending', processor=get_bool_check_mark),
        is_staff = columns.BooleanColumn(sources='is_staff', processor=get_bool_check_mark),
        is_school_contact = columns.BooleanColumn(sources='is_school_contact', processor=get_bool_check_mark),
    
        class Meta:
            columns = ['username', 'first_name', 'last_name', 'email', 'school', 'is_active', 'is_pending', 'is_staff', 'is_school_contact']
            processors = {
                'username': model_link_to_model,
            }
    
    
    class PersonDatatableView(DatatableView):
        """rrr"""
        model = Person
        datatable_class = PersonDataTable
        template_name = "example_base.html"

    def get_bool_check_mark(object, **kwargs):
        if kwargs.get('default_value', None):
            return '<span class="text-success">&#10004;</span>'
        else:
            return '<span class="text-danger">&#10008;</span>'

And the error message: 

    Traceback (most recent call last):
      File "/home/virtualenv/edgleweb/lib/python3.5/site-packages/django/core/handlers/base.py", line 149, in get_response
        response = self.process_exception_by_middleware(e, request)
      File "/home/virtualenv/edgleweb/lib/python3.5/site-packages/django/core/handlers/base.py", line 147, in get_response
        response = wrapped_callback(request, *callback_args, **callback_kwargs)
      File "/usr/lib/python3.5/contextlib.py", line 30, in inner
        return func(*args, **kwds)
      File "/home/virtualenv/edgleweb/lib/python3.5/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
        return view_func(request, *args, **kwargs)
      File "/home/virtualenv/edgleweb/lib/python3.5/site-packages/django/views/generic/base.py", line 68, in view
        return self.dispatch(request, *args, **kwargs)
      File "/home/virtualenv/edgleweb/lib/python3.5/site-packages/django/views/generic/base.py", line 88, in dispatch
        return handler(request, *args, **kwargs)
      File "/home/github/django-datatable-view/datatableview/views/base.py", line 25, in get
        return self.get_ajax(request, *args, **kwargs)
      File "/home/github/django-datatable-view/datatableview/views/base.py", line 80, in get_ajax
        response_data = self.get_json_response_object(datatable)
      File "/home/github/django-datatable-view/datatableview/views/base.py", line 42, in get_json_response_object
        datatable.populate_records()
      File "/home/github/django-datatable-view/datatableview/datatables.py", line 442, in populate_records
        objects = self.search(objects)
      File "/home/github/django-datatable-view/datatableview/datatables.py", line 470, in search
        q = search_f(column, term)
      File "/home/github/django-datatable-view/datatableview/datatables.py", line 484, in _search_column
        return column.search(self.model, terms)
      File "/home/github/django-datatable-view/datatableview/columns.py", line 365, in search
        coerced_term = handler.prep_search_value(term, lookup_type)
      File "/home/github/django-datatable-view/datatableview/columns.py", line 490, in prep_search_value
        return super(BooleanColumn, self).prep_search_value(term, lookup_type)
      File "/home/github/django-datatable-view/datatableview/columns.py", line 292, in prep_search_value
        in_bits = re.split(r',\s*', term)
      File "/home/virtualenv/edgleweb/lib/python3.5/re.py", line 203, in split
        return _compile(pattern, flags).split(string, maxsplit)
    TypeError: expected string or bytes-like object    

It does BooleanColumn's `prep_search_value` fine, where `term='true'` becomes `term=True`. Afterwards  super classes (Column) `prep_search_value` is called, where it blows up.

**Comment by doganmeh** [comment]
I tested this on example_project's `ChoiceField` view, by changing `status` field to `BooleanColumn` and it did the same thing.
