### ISSUE TITLE
Python3.6 error

### ISSUE THREAD

**Issue by doganmeh** [pivotal-energy-solutions/django-datatable-view#181]
I know it is not officially supported, but, I tested datatableview against Django1.11 with which it worked fine, however, I get the following error using it with Python3.6:
```
Traceback (most recent call last):
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python3.6/contextlib.py", line 53, in inner
    return func(*args, **kwds)
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/github/django-datatable-view/datatableview/views/base.py", line 24, in dispatch
    return self.get_ajax(request, *args, **kwargs)
  File "/home/github/django-datatable-view/datatableview/views/base.py", line 82, in get_ajax
    response_data = self.get_json_response_object(self._datatable)
  File "/home/github/django-datatable-view/datatableview/views/base.py", line 41, in get_json_response_object
    datatable.populate_records()
  File "/home/github/django-datatable-view/datatableview/datatables.py", line 464, in populate_records
    objects = self.search(objects)
  File "/home/github/django-datatable-view/datatableview/datatables.py", line 504, in search
    queryset = queryset.filter(q)
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/db/models/query.py", line 781, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/db/models/query.py", line 799, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1260, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1280, in _add_q
    current_negated, allow_joins, split_subq)
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1286, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/virtualenv/edgleweb/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1211, in build_filter
    raise FieldError('Related Field got invalid lookup: {}'.format(lookups[0]))
django.core.exceptions.FieldError: Related Field got invalid lookup: icontains

**Comment by doganmeh** [comment]
this may not be right, I am re-checking.

**Comment by doganmeh** [comment]
My bad! false alarm.

**Comment by jangeador** [comment]
what was the false alarm? I am having the same issue.
