### ISSUE TITLE
Searches from Date or DateTime fields cause error 

### ISSUE THREAD

**Issue by kuulasmaa** [pivotal-energy-solutions/django-datatable-view#183]
Searches from Date or DateTime fields do not work. Searches cause the following error: 

- 'TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.date''
or
- 'TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.datetime'' 

Searches from other type of fields seems to work but searches from Date and DateTime cause problems. However search terms like '2017-' or '2017-04' works but more complete date notations like '2017-04-2' or '2017-04-20' cause error. I have been struckling with this error for over a year. I have tried both master branch and official 0.9.0-beta.5 release. I see the same behavior by using python 3.4/3.6 and django 1.9/1.11. All these python and django version (and different combinations) leads to the same error message.

I have been wondering why nobody have reported this bug before. Am I doing something wrong?

**Test case:** 

```
class DateTest(models.Model):
    class Meta:
        managed = True
    name = models.CharField( verbose_name='Name', max_length=50, blank=False)
    date = models.DateField( verbose_name=u'DateField', blank=True, null=True)
    datetime = models.DateTimeField(verbose_name=u'DateTimeField', blank=True, null=True)

class DateTestDatatable(Datatable):    
    class Meta:
        model = DateTest
        columns = [u'name', u'date', u'datetime']
        
class DateTestDatatableView(DatatableView):
    template_name = u"sislabdb/table.html"
    model = DateTest
    datatable_class = DateTestDatatable
```
**Traceback**

Internal Server Error: /sislabdb/datetest/table/
Traceback (most recent call last):
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/contrib/auth/decorators.py", line 23, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/datatableview/views/base.py", line 24, in dispatch
    return self.get_ajax(request, *args, **kwargs)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/datatableview/views/base.py", line 82, in get_ajax
    response_data = self.get_json_response_object(self._datatable)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/datatableview/views/base.py", line 41, in get_json_response_object
    datatable.populate_records()
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/datatableview/datatables.py", line 464, in populate_records
    objects = self.search(objects)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/datatableview/datatables.py", line 504, in search
    queryset = queryset.filter(q)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/query.py", line 781, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/query.py", line 799, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1260, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1280, in _add_q
    current_negated, allow_joins, split_subq)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1286, in _add_q
    allow_joins=allow_joins, split_subq=split_subq,
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1220, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1114, in build_lookup
    return final_lookup(lhs, rhs)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/lookups.py", line 24, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/lookups.py", line 74, in get_prep_lookup
    return self.lhs.output_field.get_prep_value(self.rhs)
  File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1849, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.date'

**Comment by kuulasmaa** [comment]
I saw that this issue reporter editor stripped out underscores from traceback. The last line in traceback should have been:

`File "/home/teemu/src/py36-django111/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 1849, in get_prep_value
    return int(value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'datetime.date'
`
I am wondering why it is calling get_prep_value from IntegerField class (in `django/db/models/fields/__init__.py`). 

Regards,

Teemu

**Comment by kuulasmaa** [comment]
I investigated the problem a little bit further and found out that lookup_types year, month, day, week_day, hour, minute and second causes problems. `Column.search` and `DateColumn.prep_search_value` functions together produce column queries that are illegal. They produce queries that tries to compare e.g. day to datetime.date object (e.g. `('start_date__year', datetime.date(2017, 4 20)`). However it should compare day to int (or something else which can be converted to int).

As a temporary fix I allowed only excat, in and range lookup_types in `DateColumn `and `DateTimeColumn `(`lookup_types = ('exact', 'in', 'range')`).

I think that the primary cause of the problem lies in the line:
`date_obj = datetime.strptime(test_term, test_format)`
which tries to extract year, month, day etc. from test_term string. I will never succeed because it test_format is never legal date format string (e.g. '%Y-%m-%d %H:%M". `datetime.strptime` expects to get complete data format string and not one part (%Y, %m, %d etc.) at the time.

Regards,

Teemu

**Comment by shahmitul** [comment]
@tiliv  any solutions found???
