### ISSUE TITLE
Django 1.7 changes model registration, breaks test_app.models hack

### ISSUE THREAD

**Issue by tiliv** [pivotal-energy-solutions/django-datatable-view#56]
Sort of a trainwreck, hinging on the fact that the models dictionary in Django 1.7's internals is no longer finding our patched-in test models.  It looks like the models dictionary needs some kind of a refresh after the ``INSTALLED_APPS`` hack, before the syncdb (?)

```
Traceback (most recent call last):
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/apps/config.py", line 152, in get_model
    return self.models[model_name.lower()]
KeyError: 'relatedmodel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/serializers/python.py", line 156, in _get_model
    return apps.get_model(model_identifier)
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/apps/registry.py", line 190, in get_model
    return self.get_app_config(app_label).get_model(model_name.lower())
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/apps/config.py", line 155, in get_model
    "App '%s' doesn't have a '%s' model." % (self.label, model_name))
LookupError: App 'test_app' doesn't have a 'relatedmodel' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/serializers/json.py", line 75, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/serializers/python.py", line 93, in Deserializer
    Model = _get_model(d["model"])
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/serializers/python.py", line 158, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
django.core.serializers.base.DeserializationError: Invalid model identifier: 'test_app.RelatedModel'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/test/testcases.py", line 182, in __call__
    self._pre_setup()
  File "./datatableview/tests/testcase.py", line 18, in _pre_setup
    super(DatatableViewTestCase, self)._pre_setup()
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/test/testcases.py", line 754, in _pre_setup
    self._fixture_setup()
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/test/testcases.py", line 907, in _fixture_setup
    'skip_checks': True,
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/management/__init__.py", line 115, in call_command
    return klass.execute(*args, **defaults)
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/management/base.py", line 337, in execute
    output = self.handle(*args, **options)
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 60, in handle
    self.loaddata(fixture_labels)
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 90, in loaddata
    self.load_label(fixture_label)
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/management/commands/loaddata.py", line 141, in load_label
    for obj in objects:
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/serializers/json.py", line 81, in Deserializer
    six.reraise(DeserializationError, DeserializationError(e), sys.exc_info()[2])
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/utils/six.py", line 549, in reraise
    raise value.with_traceback(tb)
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/serializers/json.py", line 75, in Deserializer
    for obj in PythonDeserializer(objects, **options):
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/serializers/python.py", line 93, in Deserializer
    Model = _get_model(d["model"])
  File "/Users/Kaori/.virtualenvs/dtv3/lib/python3.4/site-packages/django/core/serializers/python.py", line 158, in _get_model
    raise base.DeserializationError("Invalid model identifier: '%s'" % model_identifier)
django.core.serializers.base.DeserializationError: Problem installing fixture '/Users/Kaori/Projects/Pivotal/django-datatable-view/datatableview/tests/test_app/fixtures/test_data.json': Invalid model identifier: 'test_app.RelatedModel'
```

**Comment by tiliv** [comment]
Fixed via #99
