### ISSUE TITLE
Example m2m page does not work

### ISSUE THREAD

**Issue by davidfischer-ch** [pivotal-energy-solutions/django-datatable-view#57]
I am eager to use django-datatable-view to generate tables out of my models. I am successful in playing with it excepted when I need to add a column related to a m2m relationship. Your example and my own setup does not handle it well.

http://django-datatable-view.appspot.com/many-to-many-fields/

The models (pseudo Python):

class UpscalingTask:
    keyword_set = m2m to Keyword

class Keyword:
    label = string field

The columns in configuration:

```
    datatable_options = {
        'structure_template': 'upscaling/task/table_structure.html',
        'columns': [
            ('Keywords', 'keyword_set', 'get_keywords_data')
        ]
    }
```

My various other trial and error:

```
1. ('Keywords', 'keyword_set__all', 'get_keywords_data')
2. ('Keywords', 'keyword_set__all__label', 'get_keywords_data')
3. ('Keywords', 'keyword_set__label', 'get_keywords_data')
```

The error on my own setup:

```
ERROR Internal Server Error: /fr/upscaling/task/table
Traceback (most recent call last):
  File "/home/ubuntu/cloudncode/venv/src/django/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/ubuntu/cloudncode/venv/src/django/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/home/ubuntu/cloudncode/venv/src/django-braces/braces/views/_access.py", line 66, in dispatch
    request, *args, **kwargs)
  File "/home/ubuntu/cloudncode/server/cloudncode_base/views/mixins.py", line 84, in dispatch
    return super().dispatch(request, *args, **kwargs)
  File "/home/ubuntu/cloudncode/venv/src/django/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/ubuntu/cloudncode/venv/src/django-datatable-view/datatableview/views.py", line 59, in get
    return self.get_ajax(request, *args, **kwargs)
  File "/home/ubuntu/cloudncode/venv/src/django-datatable-view/datatableview/views.py", line 304, in get_ajax
    response_data = self.get_json_response_object(object_list, total, filtered_total)
  File "/home/ubuntu/cloudncode/venv/src/django-datatable-view/datatableview/views.py", line 328, in get_json_response_object
    'aaData': [self.get_record_data(obj) for obj in object_list_page],
  File "/home/ubuntu/cloudncode/venv/src/django-datatable-view/datatableview/views.py", line 328, in <listcomp>
    'aaData': [self.get_record_data(obj) for obj in object_list_page],
  File "/home/ubuntu/cloudncode/venv/src/django-datatable-view/datatableview/views.py", line 373, in get_record_data
    column_data = self.get_column_data(i, name, obj)[0]
  File "/home/ubuntu/cloudncode/venv/src/django-datatable-view/datatableview/views.py", line 386, in get_column_data
    kwargs['default_value'] = self._get_column_data_default(instance, column)[1]
  File "/home/ubuntu/cloudncode/venv/src/django-datatable-view/datatableview/views.py", line 504, in _get_column_data_default
    value = reduce(chain_lookup, [instance] + field_name.split('__'))
  File "/home/ubuntu/cloudncode/venv/src/django-datatable-view/datatableview/views.py", line 499, in chain_lookup
    value = value()
  File "/home/ubuntu/cloudncode/venv/src/django/django/db/models/fields/related.py", line 837, in __call__
    manager = getattr(self.model, kwargs.pop('manager'))
KeyError: 'manager'
```

**Comment by utapyngo** [comment]
Thanks!
